### ISSUE TITLE
can i trust you that you will not steal my kereberos credentials?

### ISSUE THREAD

**Issue by Sujas-Aggarwal** [akki01133/ocs_iitd_captcha_solver_chrome_extension#1]

**Comment by Sujas-Aggarwal** [comment]
would love it if you can explain how this works

**Comment by ajeetkr-7** [comment]
Well the repo contains the source code of the extension. Why don't you verify if I can steal your kereberos credentials or not. Though the repo contains the build files, but it still shouldn't be a problem i guess. After all you hold both technical executive and technical co-ordinator POR at the same time :)

**Comment by Sujas-Aggarwal** [comment]
your response would have been much better without the sarcasm but looking at how your code works and how ocs actually serves the captcha, I think that I deserved it

**Comment by ajeetkr-7** [comment]
> your response would have been much better without the sarcasm

Meant no humiliation boy...but my sarcastic words made you find out things for yourself. Wasn't that much cooler than Ime just showing you the source code 😄

**Comment by ajeetkr-7** [comment]
If you r interested in more of this OCS thing, you can look into @as1605 flutter project here: https://github.com/as1605/OCS-Tracker-App

Happy coding :)

**Comment by Sujas-Aggarwal** [comment]
Thanks, by the way, are you an alumni of IITD?

**Comment by ajeetkr-7** [comment]
Yes I am.
